<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Vishal-PC" ignored="0" name="RetryTest" tests="8" failures="2" timestamp="24 Sep 2018 07:52:35 GMT" time="112.369" errors="0">
  <testcase name="test1" time="0.017" classname="com.crm.qa.testcases.MyRetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.crm.qa.testcases.MyRetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.crm.qa.testcases.MyRetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="com.crm.qa.testcases.MyRetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.crm.qa.testcases.MyRetryTest.test1(MyRetryTest.java:38)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="com.crm.qa.testcases.MyRetryTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="com.crm.qa.testcases.MyRetryTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="com.crm.qa.testcases.MyRetryTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.crm.qa.testcases.MyRetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.crm.qa.testcases.MyRetryTest.test2(MyRetryTest.java:44)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- RetryTest -->
